Attribute VB_Name = "AllKeyAssign"

Dim keybinde As String

Sub toggleVimKeybinde()'{{{
	If keybinde <> "off" Then
		Call AllKeyAssign_reset()
		keybinde = "off"
	Else
		Call AllKeyToAssesKeyFunc()
	End If
End Sub'}}}

Function AllKeyAssign_dummy() '{{{
    Application.OnKey "a", "dummy"
    Application.OnKey "b", "dummy"
    Application.OnKey "c", "dummy"
    Application.OnKey "d", "dummy"
    Application.OnKey "e", "dummy"
    Application.OnKey "f", "dummy"
    Application.OnKey "g", "dummy"
    Application.OnKey "h", "dummy"
    Application.OnKey "i", "dummy"
    Application.OnKey "j", "dummy"
    Application.OnKey "k", "dummy"
    Application.OnKey "l", "dummy"
    Application.OnKey "m", "dummy"
    Application.OnKey "n", "dummy"
    Application.OnKey "o", "dummy"
    Application.OnKey "p", "dummy"
    Application.OnKey "q", "dummy"
    Application.OnKey "r", "dummy"
    Application.OnKey "s", "dummy"
    Application.OnKey "t", "dummy"
    Application.OnKey "u", "dummy"
    Application.OnKey "v", "dummy"
    Application.OnKey "w", "dummy"
    Application.OnKey "x", "dummy"
    Application.OnKey "y", "dummy"
    Application.OnKey "z", "dummy"
    
    Application.OnKey "0", "dummy"
    Application.OnKey "1", "dummy"
    Application.OnKey "2", "dummy"
    Application.OnKey "3", "dummy"
    Application.OnKey "4", "dummy"
    Application.OnKey "5", "dummy"
    Application.OnKey "6", "dummy"
    Application.OnKey "7", "dummy"
    Application.OnKey "8", "dummy"
    Application.OnKey "9", "dummy"
    
    Application.OnKey "=", "dummy"
    Application.OnKey "-", "dummy"
    Application.OnKey "{^}", "dummy"
    Application.OnKey "@", "dummy"
    Application.OnKey "{[}", "dummy"
    Application.OnKey ";", "dummy"
    Application.OnKey ":", "dummy"
    Application.OnKey "{]}", "dummy"
    Application.OnKey ",", "dummy" '
    Application.OnKey ".", "dummy"
    Application.OnKey "/", "dummy" '
    
    Application.OnKey "+a", "dummy"
    Application.OnKey "+b", "dummy"
    Application.OnKey "+c", "dummy"
    Application.OnKey "+d", "dummy"
    Application.OnKey "+e", "dummy"
    Application.OnKey "+f", "dummy"
    Application.OnKey "+g", "dummy"
    Application.OnKey "+h", "dummy"
    Application.OnKey "+i", "dummy"
    Application.OnKey "+j", "dummy"
    Application.OnKey "+k", "dummy"
    Application.OnKey "+l", "dummy"
    Application.OnKey "+m", "dummy"
    Application.OnKey "+n", "dummy"
    Application.OnKey "+o", "dummy"
    Application.OnKey "+p", "dummy"
    Application.OnKey "+q", "dummy"
    Application.OnKey "+r", "dummy"
    Application.OnKey "+s", "dummy"
    Application.OnKey "+t", "dummy"
    Application.OnKey "+u", "dummy"
    Application.OnKey "+v", "dummy"
    Application.OnKey "+w", "dummy"
    Application.OnKey "+x", "dummy"
    Application.OnKey "+y", "dummy"
    Application.OnKey "+z", "dummy"
    
    Application.OnKey "+0", "dummy"
    Application.OnKey "+1", "dummy"
    Application.OnKey "+2", "dummy"
    Application.OnKey "+3", "dummy"
    Application.OnKey "+4", "dummy"
    Application.OnKey "+5", "dummy"
    Application.OnKey "+6", "dummy"
    Application.OnKey "+7", "dummy"
    Application.OnKey "+8", "dummy"
    Application.OnKey "+9", "dummy"
End Function '}}}

Function AllKeyAssign_reset() '{{{
    Application.OnKey "a"
    Application.OnKey "b"
    Application.OnKey "c"
    Application.OnKey "d"
    Application.OnKey "e"
    Application.OnKey "f"
    Application.OnKey "g"
    Application.OnKey "h"
    Application.OnKey "i"
    Application.OnKey "j"
    Application.OnKey "k"
    Application.OnKey "l"
    Application.OnKey "m"
    Application.OnKey "n"
    Application.OnKey "o"
    Application.OnKey "p"
    Application.OnKey "q"
    Application.OnKey "r"
    Application.OnKey "s"
    Application.OnKey "t"
    Application.OnKey "u"
    Application.OnKey "v"
    Application.OnKey "w"
    Application.OnKey "x"
    Application.OnKey "y"
    Application.OnKey "z"
    
    Application.OnKey "0"
    Application.OnKey "1"
    Application.OnKey "2"
    Application.OnKey "3"
    Application.OnKey "4"
    Application.OnKey "5"
    Application.OnKey "6"
    Application.OnKey "7"
    Application.OnKey "8"
    Application.OnKey "9"
    
    Application.OnKey "="
    Application.OnKey "-"
    Application.OnKey "{^}"
    Application.OnKey "?"
    Application.OnKey "@"
    Application.OnKey "{[}"
    Application.OnKey ";"
    Application.OnKey ":"
    Application.OnKey "{]}"
    Application.OnKey "."
    
    Application.OnKey "+a"
    Application.OnKey "+b"
    Application.OnKey "+c"
    Application.OnKey "+d"
    Application.OnKey "+e"
    Application.OnKey "+f"
    Application.OnKey "+g"
    Application.OnKey "+h"
    Application.OnKey "+i"
    Application.OnKey "+j"
    Application.OnKey "+k"
    Application.OnKey "+l"
    Application.OnKey "+m"
    Application.OnKey "+n"
    Application.OnKey "+o"
    Application.OnKey "+p"
    Application.OnKey "+q"
    Application.OnKey "+r"
    Application.OnKey "+s"
    Application.OnKey "+t"
    Application.OnKey "+u"
    Application.OnKey "+v"
    Application.OnKey "+w"
    Application.OnKey "+x"
    Application.OnKey "+y"
    Application.OnKey "+z"
    
    Application.OnKey "+0"
    Application.OnKey "+1"
    Application.OnKey "+2"
    Application.OnKey "+3"
    Application.OnKey "+4"
    Application.OnKey "+5"
    Application.OnKey "+6"
    Application.OnKey "+7"
    Application.OnKey "+8"
    Application.OnKey "+9"
    
    Application.OnKey "+-"
    Application.OnKey "+{^}"
    Application.OnKey "+?"
    Application.OnKey "+@"
    Application.OnKey "+{[}"
    Application.OnKey "+;"
    Application.OnKey "+:"
    Application.OnKey "+{]}"
    Application.OnKey "<"
    Application.OnKey "+."
    Application.OnKey "+/"
    Application.OnKey "_"
    
    'Ctrl
    Application.OnKey "^a"
    Application.OnKey "^b"
    Application.OnKey "^c"
    Application.OnKey "^d"
    Application.OnKey "^e"
    Application.OnKey "^f"
    Application.OnKey "^g"
    Application.OnKey "^h"
    Application.OnKey "^i"
    Application.OnKey "^j"
    Application.OnKey "^k"
    Application.OnKey "^l"
    Application.OnKey "^m"
    Application.OnKey "^n"
    Application.OnKey "^o"
    Application.OnKey "^p"
    Application.OnKey "^q"
    Application.OnKey "^r"
    Application.OnKey "^s"
    Application.OnKey "^t"
    Application.OnKey "^u"
    Application.OnKey "^v"
    Application.OnKey "^w"
    Application.OnKey "^x"
    Application.OnKey "^y"
    Application.OnKey "^z"
    
    Application.OnKey "^0"
    Application.OnKey "^1"
    Application.OnKey "^2"
    Application.OnKey "^3"
    Application.OnKey "^4"
    Application.OnKey "^5"
    Application.OnKey "^6"
    Application.OnKey "^7"
    Application.OnKey "^8"
    Application.OnKey "^9"
    
    Application.OnKey "^-"
    Application.OnKey "^{^}"
    Application.OnKey "^?"
    Application.OnKey "^@"
    Application.OnKey "^{[}"
    Application.OnKey "^;"
    Application.OnKey "^:"
    Application.OnKey "^{]}"
    Application.OnKey "^."
    
    Application.OnKey "^+a"
    Application.OnKey "^+b"
    Application.OnKey "^+c"
    Application.OnKey "^+d"
    Application.OnKey "^+e"
    Application.OnKey "^+f"
    Application.OnKey "^+g"
    Application.OnKey "^+h"
    Application.OnKey "^+i"
    Application.OnKey "^+j"
    Application.OnKey "^+k"
    Application.OnKey "^+l"
    Application.OnKey "^+m"
    Application.OnKey "^+n"
    Application.OnKey "^+o"
    Application.OnKey "^+p"
    Application.OnKey "^+q"
    Application.OnKey "^+r"
    Application.OnKey "^+s"
    Application.OnKey "^+t"
    Application.OnKey "^+u"
    Application.OnKey "^+v"
    Application.OnKey "^+w"
    Application.OnKey "^+x"
    Application.OnKey "^+y"
    Application.OnKey "^+z"
    
    Application.OnKey "^+0"
    Application.OnKey "^+1"
    Application.OnKey "^+2"
    Application.OnKey "^+3"
    Application.OnKey "^+4"
    Application.OnKey "^+5"
    Application.OnKey "^+6"
    Application.OnKey "^+7"
    Application.OnKey "^+8"
    Application.OnKey "^+9"
    
    Application.OnKey "^+-"
    Application.OnKey "^+{^}"
    Application.OnKey "^+?"
    Application.OnKey "^+@"
    Application.OnKey "^+{[}"
    Application.OnKey "^+;"
    Application.OnKey "^+:"
    Application.OnKey "^+{]}"
    Application.OnKey "^<"
    Application.OnKey "^+."
    Application.OnKey "^+/"
    Application.OnKey "^_"
End Function '}}}
