Attribute VB_Name = "user_configure"

Public Sub init() '{{{
	call mykeymap
End Sub '}}}

private sub mykeymap() '{{{
	Call nmap("<HOME>", "move_head")
	Call nmap("<END>", "move_tail")
	Call nmap("t", "insertColumnRight")
	Call nmap("T", "insertColumnLeft")
	Call nmap(";n", "InteriorColor(0)")
	Call nmap(";r", "InteriorColor(3)")
	Call nmap(";b", "InteriorColor(5)")
	Call nmap(";y", "InteriorColor(6)")
	Call nmap(";d", "InteriorColor(15)")
	Call nmap("m", "merge")
	Call nmap("M", "unmerge")
	Call nmap(">", "biggerFonts")
	Call nmap("<<", "smallerFonts")
	Call nmap("z", "SetRuledLines")
	Call nmap("Z", "UnsetRuledLines")
	Call nmap("F9", "toggleVimKeybinde")
	Call nmap("F10", "-a updatemodules(ActiveWorkbook.Name)")
	Call nmap("<c-r>", "update")
	Call nmap("+", "ZoomInWindow")
	Call nmap("-", "ZoomOutWindow")
	Call nmap("gs", "SortCurrentColumn")
	Call nmap("gF", "focusFromScratch")
	Call nmap("gf", "focus")
	Call nmap("g-", "exclude")
	Call nmap("gc", "filterOff")
	Call nmap("H", "ex_left")
	Call nmap("J", "ex_below")
	Call nmap("K", "ex_up")
	Call nmap("L", "ex_right")
	Call nmap(",m", "unite mru")
	Call nmap(",s", "unite sheet")
	Call nmap(",b", "unite book")
	Call nmap(",p", "unite project")
	Call nmap(",f", "unite filter")
	Call nmap("tl", "ActivateLeftSheet")
	Call nmap("th", "ActivateRightSheet")
	Call nmap("tL", "ActivateLastSheet")
	Call nmap("tH", "ActivateFirstSheet")
	Call vmap("<HOME>", "v_move_head")
	Call vmap("<END>", "v_move_tail")
	Call vmap(";n", "visual_operation InteriorColor(0)")
	Call vmap(";r", "visual_operation InteriorColor(3)")
	Call vmap(";b", "visual_operation InteriorColor(5)")
	Call vmap(";y", "visual_operation InteriorColor(6)")
	Call vmap(";d", "visual_operation InteriorColor(15)")
	Call vmap("m", "visual_operation merge")
	Call vmap("M", "visual_operation unmerge")
	Call vmap(">", "visual_operation biggerFonts")
	Call vmap("<<", "visual_operation smallerFonts")
	Call vmap("z", "visual_operation SetRuledLines")
	Call vmap("Z", "visual_operation UnsetRuledLines")
	Call lvmap(";n", "visual_operation InteriorColor(0)")
	Call lvmap(";r", "visual_operation InteriorColor(3)")
	Call lvmap(";b", "visual_operation InteriorColor(5)")
	Call lvmap(";y", "visual_operation InteriorColor(6)")
	Call lvmap(";d", "visual_operation InteriorColor(15)")
	Call lvmap("m", "visual_operation merge")
	Call lvmap("M", "visual_operation unmerge")
	Call lvmap(">", "visual_operation biggerFonts")
	Call lvmap("<<", "visual_operation smallerFonts")
	Call lvmap("z", "visual_operation SetRuledLines")
	Call lvmap("Z", "visual_operation UnsetRuledLines")
end sub '}}}
